# Generated by Django 6.0.3 on 2026-04-07 16:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('name_en', models.CharField(verbose_name='Название на английском')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='anime_poster', verbose_name='Постер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_year', models.DateField(verbose_name='Дата выхода')),
                ('shikimori_rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг Shikimori')),
                ('our_rating', models.FloatField(default=0, verbose_name='Наш рейтинг')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='CustemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_color', models.CharField(choices=[('Красный', '🔴 Красный'), ('Оранжевый', '🟠 Оранжевый'), ('Жёлтый', '🟡 Жёлтый'), ('Зелёный', '🟢 Зелёный'), ('Синий', '🔵 Синий'), ('Фиолетовый', '🟣 Фиолетовый'), ('Коричневый', '🟤 Коричневый'), ('Чёрный', '⚫️ Чёрный'), ('Белый', '⚪️ Белый')], max_length=20, verbose_name='Цвет глаз')),
                ('hair_color', models.CharField(choices=[('Красный', '🔴 Красный'), ('Оранжевый', '🟠 Оранжевый'), ('Жёлтый', '🟡 Жёлтый'), ('Зелёный', '🟢 Зелёный'), ('Синий', '🔵 Синий'), ('Фиолетовый', '🟣 Фиолетовый'), ('Коричневый', '🟤 Коричневый'), ('Чёрный', '⚫️ Чёрный'), ('Белый', '⚪️ Белый')], max_length=20, verbose_name='Цвет волос')),
                ('gender', models.CharField(choices=[('Мужской', '♂️ Мужской'), ('Женский', '♀️ Женский'), ('Неизвестно', '❓ Неизвестно')], max_length=20, verbose_name='Пол')),
                ('species', models.CharField(choices=[('Человек', 'Человек'), ('Демон', 'Демон'), ('Ангел', 'Ангел'), ('Гном', 'Гном'), ('Эльф', 'Эльф'), ('Неизвестно', 'Неизвестно')], max_length=20, verbose_name='Раса')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('gg', models.CharField(blank=True, choices=[('Главный герой', '⭐ Главный герой')], default=None, max_length=20, null=True, verbose_name='Роль')),
                ('image', models.ImageField(upload_to='characters/', verbose_name='Изображение')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.CharField(max_length=600, verbose_name='Содержание')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.anime', verbose_name='Аниме')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comments', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='core.genre', verbose_name='Жанры'),
        ),
        migrations.CreateModel(
            name='SeasonAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons_number', models.PositiveIntegerField(verbose_name='Номер сезона')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('episode_number', models.PositiveIntegerField(verbose_name='Номер эпизода')),
                ('video', models.FileField(upload_to='episodes/', verbose_name='Видео')),
                ('poster', models.ImageField(upload_to='episode_posters/', verbose_name='Постер')),
                ('ss_year', models.CharField(default='Весна', verbose_name='Сезон')),
                ('year', models.CharField(default=2026, verbose_name='Год')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.seasonanime', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Просмотрено (сек)')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime', verbose_name='Аниме')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.episode', verbose_name='Эпизод')),
                ('season_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seasonanime', verbose_name='Сезон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': 'История просмотров',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Буду смотреть'), ('watched', 'Просмотрено')], max_length=10, verbose_name='Статус')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime', verbose_name='Аниме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'unique_together': {('user', 'anime')},
            },
        ),
        migrations.CreateModel(
            name='Reating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[('1', '⭐1'), ('2', '⭐2'), ('3', '⭐3'), ('4', '⭐4'), ('5', '⭐5')], max_length=5, verbose_name='Оценка')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime', verbose_name='Аниме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
