# Generated by Django 6.0.3 on 2026-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custemuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='custemuser',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
