# Generated by Django 6.0.3 on 2026-03-13 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.episode')),
                ('season_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seasonanime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
