# Generated by Django 6.0.3 on 2026-03-25 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.AlterModelOptions(
            name='backgroundpicture',
            options={'verbose_name': 'Фоновое изображение', 'verbose_name_plural': 'Фоновые изображения'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='custemuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Эпизод', 'verbose_name_plural': 'Эпизоды'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='reating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='seasonanime',
            options={'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезоны'},
        ),
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'verbose_name': 'История просмотра', 'verbose_name_plural': 'История просмотров'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='core.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='anime_poster', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='our_rating',
            field=models.FloatField(default=0, verbose_name='Наш рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_year',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='shikimori_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг Shikimori'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='ss_year',
            field=models.CharField(default='Весна', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.CharField(default=2026, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='backgroundpicture',
            name='image',
            field=models.ImageField(upload_to='background/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='status',
            field=models.CharField(choices=[('planned', 'Буду смотреть'), ('watched', 'Просмотрено')], max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='character',
            name='eye_color',
            field=models.CharField(choices=[('Красный', '🔴 Красный'), ('Оранжевый', '🟠 Оранжевый'), ('Жёлтый', '🟡 Жёлтый'), ('Зелёный', '🟢 Зелёный'), ('Синий', '🔵 Синий'), ('Фиолетовый', '🟣 Фиолетовый'), ('Коричневый', '🟤 Коричневый'), ('Чёрный', '⚫️ Чёрный'), ('Белый', '⚪️ Белый')], max_length=20, verbose_name='Цвет глаз'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Мужской', '♂️ Мужской'), ('Женский', '♀️ Женский'), ('Неизвестно', '❓ Неизвестно')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gg',
            field=models.CharField(blank=True, choices=[('Главный герой', '⭐ Главный герой')], default=None, max_length=20, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(choices=[('Красный', '🔴 Красный'), ('Оранжевый', '🟠 Оранжевый'), ('Жёлтый', '🟡 Жёлтый'), ('Зелёный', '🟢 Зелёный'), ('Синий', '🔵 Синий'), ('Фиолетовый', '🟣 Фиолетовый'), ('Коричневый', '🟤 Коричневый'), ('Чёрный', '⚫️ Чёрный'), ('Белый', '⚪️ Белый')], max_length=20, verbose_name='Цвет волос'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(upload_to='characters/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(choices=[('Человек', 'Человек'), ('Демон', 'Демон'), ('Ангел', 'Ангел'), ('Гном', 'Гном'), ('Эльф', 'Эльф'), ('Неизвестно', 'Неизвестно')], max_length=20, verbose_name='Раса'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=600, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comments', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='custemuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='custemuser',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(verbose_name='Номер эпизода'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='poster',
            field=models.ImageField(upload_to='episode_posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.seasonanime', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(upload_to='episodes/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='reating',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='reating',
            name='point',
            field=models.CharField(choices=[('1', '⭐1'), ('2', '⭐2'), ('3', '⭐3'), ('4', '⭐4'), ('5', '⭐5')], max_length=5, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='reating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='seasonanime',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='seasonanime',
            name='seasons_number',
            field=models.PositiveIntegerField(verbose_name='Номер сезона'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime', verbose_name='Аниме'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.episode', verbose_name='Эпизод'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='season_anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seasonanime', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотрено (сек)'),
        ),
    ]
